//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMenu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int MealTypeId { get; set; }
    
        public virtual MealType MealType { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
