//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMenu.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Meals = new HashSet<Meal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RestaurantCategoryId { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual RestaurantCategory RestaurantCategory { get; set; }
    }
}
